# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.windows = QtWidgets.QStackedWidget(self.centralwidget)
        self.windows.setGeometry(QtCore.QRect(0, 50, 800, 550))
        self.windows.setObjectName("windows")

        self.page_routs = QtWidgets.QWidget()
        self.page_routs.setObjectName("page_routs")
        self.routs_btns = QtWidgets.QWidget(self.page_routs)
        self.routs_btns.setGeometry(QtCore.QRect(0, 0, 800, 50))
        self.routs_btns.setStyleSheet("background-color: #B0C4DE;")
        self.routs_btns.setObjectName("routs_btns")

        self.btn_rout_filter = QtWidgets.QPushButton(self.routs_btns)
        self.btn_rout_filter.setGeometry(QtCore.QRect(670, 10, 120, 30))
        self.btn_rout_filter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_rout_filter.setStyleSheet("QPushButton {\n"
                                             "      background-color: #0000FF;\n"
                                             "      border: none;\n"
                                             "    border-bottom: 3px solid grey;\n"
                                             "      color: white;\n"
                                             "     padding: 3px 3px;\n"
                                             "}\n"
                                             "QPushButton:hover {\n"
                                             "    border-bottom: 3px solid black;\n"
                                             "    background-color: #0000CD;\n"
                                             "}")
        self.btn_rout_filter.setObjectName("btn_rout_filter")
        self.btn_rout_filter.setText("Фильтр")

        self.btn_addRout = QtWidgets.QPushButton(self.routs_btns)
        self.btn_addRout.setGeometry(QtCore.QRect(10, 10, 120, 30))
        self.btn_addRout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_addRout.setStyleSheet("QPushButton {\n"
"      background-color: #0000FF;\n"
"      border: none;\n"
"    border-bottom: 3px solid grey;\n"
"      color: white;\n"
"     padding: 3px 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-bottom: 3px solid black;\n"
"    background-color: #0000CD;\n"
"}")
        self.btn_addRout.setObjectName("btn_addRout")
        self.btn_deleteRout = QtWidgets.QPushButton(self.routs_btns)
        self.btn_deleteRout.setGeometry(QtCore.QRect(140, 10, 120, 30))
        self.btn_deleteRout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_deleteRout.setStyleSheet("QPushButton {\n"
"      background-color: #0000FF;\n"
"      border: none;\n"
"    border-bottom: 3px solid grey;\n"
"      color: white;\n"
"     padding: 3px 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-bottom: 3px solid black;\n"
"    background-color: #0000CD;\n"
"}")
        self.btn_deleteRout.setObjectName("btn_deleteRout")
        self.btn_editRout = QtWidgets.QPushButton(self.routs_btns)
        self.btn_editRout.setGeometry(QtCore.QRect(270, 10, 120, 30))
        self.btn_editRout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_editRout.setStyleSheet("QPushButton {\n"
"      background-color: #0000FF;\n"
"      border: none;\n"
"    border-bottom: 3px solid grey;\n"
"      color: white;\n"
"     padding: 3px 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-bottom: 3px solid black;\n"
"    background-color: #0000CD;\n"
"}")
        self.btn_editRout.setObjectName("btn_editRout")
        self.tableRouts = QtWidgets.QTableWidget(self.page_routs)
        self.tableRouts.setGeometry(QtCore.QRect(0, 50, 800, 500))
        self.tableRouts.setAutoFillBackground(False)
        self.tableRouts.setStyleSheet("")
        self.tableRouts.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableRouts.setTabKeyNavigation(False)
        self.tableRouts.setCornerButtonEnabled(False)
        self.tableRouts.setRowCount(0)
        self.tableRouts.setObjectName("tableRouts")
        self.tableRouts.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableRouts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRouts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        item.setFont(font)
        self.tableRouts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRouts.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRouts.setHorizontalHeaderItem(4, item)
        self.tableRouts.horizontalHeader().setDefaultSectionSize(150)
        self.tableRouts.horizontalHeader().setMinimumSectionSize(150)
        self.tableRouts.verticalHeader().setDefaultSectionSize(40)
        self.tableRouts.verticalHeader().setHighlightSections(True)
        self.tableRouts.verticalHeader().setMinimumSectionSize(40)
        self.windows.addWidget(self.page_routs)
        self.page_drivers = QtWidgets.QWidget()
        self.page_drivers.setObjectName("page_drivers")
        self.drivers_btns = QtWidgets.QWidget(self.page_drivers)
        self.drivers_btns.setGeometry(QtCore.QRect(0, 0, 800, 50))
        self.drivers_btns.setStyleSheet("background-color: #B0C4DE;")
        self.drivers_btns.setObjectName("drivers_btns")

        self.btn_driver_filter = QtWidgets.QPushButton(self.drivers_btns)
        self.btn_driver_filter.setGeometry(QtCore.QRect(670, 10, 120, 30))
        self.btn_driver_filter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_driver_filter.setStyleSheet("QPushButton {\n"
                                         "      background-color: #0000FF;\n"
                                         "      border: none;\n"
                                         "    border-bottom: 3px solid grey;\n"
                                         "      color: white;\n"
                                         "     padding: 3px 3px;\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    border-bottom: 3px solid black;\n"
                                         "    background-color: #0000CD;\n"
                                         "}")
        self.btn_driver_filter.setObjectName("btn_driver_filter")
        self.btn_driver_filter.setText("Фильтр")

        self.btn_addDriver = QtWidgets.QPushButton(self.drivers_btns)
        self.btn_addDriver.setGeometry(QtCore.QRect(10, 10, 120, 30))
        self.btn_addDriver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_addDriver.setStyleSheet("QPushButton {\n"
"      background-color: #0000FF;\n"
"      border: none;\n"
"    border-bottom: 3px solid grey;\n"
"      color: white;\n"
"     padding: 3px 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-bottom: 3px solid black;\n"
"    background-color: #0000CD;\n"
"}")
        self.btn_addDriver.setObjectName("btn_addDriver")
        self.btn_deleteDriver = QtWidgets.QPushButton(self.drivers_btns)
        self.btn_deleteDriver.setGeometry(QtCore.QRect(140, 10, 120, 30))
        self.btn_deleteDriver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_deleteDriver.setStyleSheet("QPushButton {\n"
"      background-color: #0000FF;\n"
"      border: none;\n"
"    border-bottom: 3px solid grey;\n"
"      color: white;\n"
"     padding: 3px 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-bottom: 3px solid black;\n"
"    background-color: #0000CD;\n"
"}")
        self.btn_deleteDriver.setObjectName("btn_deleteDriver")
        self.btn_editDriver = QtWidgets.QPushButton(self.drivers_btns)
        self.btn_editDriver.setGeometry(QtCore.QRect(270, 10, 120, 30))
        self.btn_editDriver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_editDriver.setStyleSheet("QPushButton {\n"
"      background-color: #0000FF;\n"
"      border: none;\n"
"    border-bottom: 3px solid grey;\n"
"      color: white;\n"
"     padding: 3px 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-bottom: 3px solid black;\n"
"    background-color: #0000CD;\n"
"}")
        self.btn_editDriver.setObjectName("btn_editDriver")
        self.tableDrivers = QtWidgets.QTableWidget(self.page_drivers)
        self.tableDrivers.setGeometry(QtCore.QRect(0, 50, 800, 500))
        self.tableDrivers.setAutoFillBackground(False)
        self.tableDrivers.setStyleSheet("")
        self.tableDrivers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableDrivers.setTabKeyNavigation(False)
        self.tableDrivers.setCornerButtonEnabled(False)
        self.tableDrivers.setRowCount(0)
        self.tableDrivers.setObjectName("tableDrivers")
        self.tableDrivers.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableDrivers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDrivers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        item.setFont(font)
        self.tableDrivers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDrivers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDrivers.setHorizontalHeaderItem(4, item)
        self.tableDrivers.horizontalHeader().setDefaultSectionSize(150)
        self.tableDrivers.horizontalHeader().setMinimumSectionSize(150)
        self.tableDrivers.verticalHeader().setDefaultSectionSize(40)
        self.tableDrivers.verticalHeader().setHighlightSections(True)
        self.tableDrivers.verticalHeader().setMinimumSectionSize(40)
        self.windows.addWidget(self.page_drivers)
        self.page_workDone = QtWidgets.QWidget()
        self.page_workDone.setObjectName("page_workDone")
        self.workDone_btns = QtWidgets.QWidget(self.page_workDone)
        self.workDone_btns.setGeometry(QtCore.QRect(0, 0, 800, 50))
        self.workDone_btns.setStyleSheet("background-color: #B0C4DE;")
        self.workDone_btns.setObjectName("workDone_btns")

        self.btn_wd_filter = QtWidgets.QPushButton(self.workDone_btns)
        self.btn_wd_filter.setGeometry(QtCore.QRect(670, 10, 120, 30))
        self.btn_wd_filter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_wd_filter.setStyleSheet("QPushButton {\n"
                                           "      background-color: #0000FF;\n"
                                           "      border: none;\n"
                                           "    border-bottom: 3px solid grey;\n"
                                           "      color: white;\n"
                                           "     padding: 3px 3px;\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    border-bottom: 3px solid black;\n"
                                           "    background-color: #0000CD;\n"
                                           "}")
        self.btn_wd_filter.setObjectName("btn_wd_filter")
        self.btn_wd_filter.setText("Фильтр")

        self.btn_addWorkDone = QtWidgets.QPushButton(self.workDone_btns)
        self.btn_addWorkDone.setGeometry(QtCore.QRect(10, 10, 120, 30))
        self.btn_addWorkDone.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_addWorkDone.setStyleSheet("QPushButton {\n"
"      background-color: #0000FF;\n"
"      border: none;\n"
"    border-bottom: 3px solid grey;\n"
"      color: white;\n"
"     padding: 3px 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-bottom: 3px solid black;\n"
"    background-color: #0000CD;\n"
"}")
        self.btn_addWorkDone.setObjectName("btn_addWorkDone")
        self.btn_deleteWorkDone = QtWidgets.QPushButton(self.workDone_btns)
        self.btn_deleteWorkDone.setGeometry(QtCore.QRect(140, 10, 120, 30))
        self.btn_deleteWorkDone.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_deleteWorkDone.setStyleSheet("QPushButton {\n"
"      background-color: #0000FF;\n"
"      border: none;\n"
"    border-bottom: 3px solid grey;\n"
"      color: white;\n"
"     padding: 3px 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-bottom: 3px solid black;\n"
"    background-color: #0000CD;\n"
"}")
        self.btn_deleteWorkDone.setObjectName("btn_deleteWorkDone")
        self.btn_editWorkDone = QtWidgets.QPushButton(self.workDone_btns)
        self.btn_editWorkDone.setGeometry(QtCore.QRect(270, 10, 120, 30))
        self.btn_editWorkDone.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_editWorkDone.setStyleSheet("QPushButton {\n"
"      background-color: #0000FF;\n"
"      border: none;\n"
"    border-bottom: 3px solid grey;\n"
"      color: white;\n"
"     padding: 3px 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-bottom: 3px solid black;\n"
"    background-color: #0000CD;\n"
"}")
        self.btn_editWorkDone.setObjectName("btn_editWorkDone")
        self.tableWorkDone = QtWidgets.QTableWidget(self.page_workDone)
        self.tableWorkDone.setGeometry(QtCore.QRect(0, 50, 800, 500))
        self.tableWorkDone.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWorkDone.setTabKeyNavigation(False)
        self.tableWorkDone.setCornerButtonEnabled(False)
        self.tableWorkDone.setRowCount(0)
        self.tableWorkDone.setObjectName("tableWorkDone")
        self.tableWorkDone.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWorkDone.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()

        self.tableWorkDone.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWorkDone.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        item.setFont(font)
        self.tableWorkDone.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWorkDone.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWorkDone.setHorizontalHeaderItem(5, item)
        self.tableWorkDone.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        self.tableWorkDone.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        self.tableWorkDone.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        self.tableWorkDone.horizontalHeader().setSectionResizeMode(3, QtWidgets.QHeaderView.Interactive)
        self.tableWorkDone.horizontalHeader().setSectionResizeMode(4, QtWidgets.QHeaderView.Interactive)
        self.tableWorkDone.horizontalHeader().setSectionResizeMode(5, QtWidgets.QHeaderView.ResizeToContents)
        self.tableWorkDone.horizontalHeader().setDefaultSectionSize(200)
        self.tableWorkDone.horizontalHeader().setMinimumSectionSize(30)
        self.tableWorkDone.verticalHeader().setDefaultSectionSize(40)
        self.tableWorkDone.verticalHeader().setHighlightSections(True)
        self.tableWorkDone.verticalHeader().setMinimumSectionSize(40)
        self.windows.addWidget(self.page_workDone)
        self.menu = QtWidgets.QWidget(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(0, 0, 800, 50))
        self.menu.setStyleSheet("background-color: #B0C4DE;\n"
"border-bottom: 1px solid black;")
        self.menu.setObjectName("menu")
        self.btn_page_routs = QtWidgets.QPushButton(self.menu)
        self.btn_page_routs.setGeometry(QtCore.QRect(72, 3, 170, 45))
        self.btn_page_routs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_page_routs.setStyleSheet("QPushButton {\n"
"      background-color: #04AA6D;\n"
"      border: none;\n"
"    border-bottom: 3px solid grey;\n"
"    border-top-left-radius: 15px;\n"
"    border-bottom-right-radius: 15px;\n"
"      color: white;\n"
"     padding: 3px 3px;\n"
"     font-size: 16px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-bottom: 3px solid black;\n"
"    background-color: #02784d;\n"
"}")
        self.btn_page_routs.setObjectName("btn_page_routs")
        self.btn_page_drivers = QtWidgets.QPushButton(self.menu)
        self.btn_page_drivers.setGeometry(QtCore.QRect(314, 3, 170, 45))
        self.btn_page_drivers.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_page_drivers.setStyleSheet("QPushButton {\n"
"      background-color: #04AA6D;\n"
"      border: none;\n"
"    border-bottom: 3px solid grey;\n"
"    border-top-left-radius: 15px;\n"
"    border-bottom-right-radius: 15px;\n"
"      color: white;\n"
"     padding: 3px 3px;\n"
"     font-size: 16px;\n"
"}\n"
"QPushButton::hover {\n"
"    border-bottom: 3px solid black;\n"
"    background-color: #02784d;\n"
"}")
        self.btn_page_drivers.setObjectName("btn_page_drivers")
        self.btn_page_workDone = QtWidgets.QPushButton(self.menu)
        self.btn_page_workDone.setGeometry(QtCore.QRect(556, 3, 170, 45))
        self.btn_page_workDone.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_page_workDone.setStyleSheet("QPushButton {\n"
"      background-color: #04AA6D;\n"
"      border: none;\n"
"    border-bottom: 3px solid grey;\n"
"    border-top-left-radius: 15px;\n"
"    border-bottom-right-radius: 15px;\n"
"      color: white;\n"
"     padding: 3px 3px;\n"
"     font-size: 16px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-bottom: 3px solid black;\n"
"    background-color: #02784d;\n"
"}")
        self.btn_page_workDone.setObjectName("btn_page_workDone")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.windows.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_addRout.setText(_translate("MainWindow", "Добавить маршрут"))
        self.btn_deleteRout.setText(_translate("MainWindow", "Удалить маршрут"))
        self.btn_editRout.setText(_translate("MainWindow", "Изменить маршрут"))
        item = self.tableRouts.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Код маршрута"))
        item = self.tableRouts.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название"))
        item = self.tableRouts.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Дальность"))
        item = self.tableRouts.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Время в пути"))
        item = self.tableRouts.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Оплата"))
        self.btn_addDriver.setText(_translate("MainWindow", "Добавить водителя"))
        self.btn_deleteDriver.setText(_translate("MainWindow", "Удалить водителя"))
        self.btn_editDriver.setText(_translate("MainWindow", "Изменить данные"))
        item = self.tableDrivers.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Код водителя"))
        item = self.tableDrivers.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Фамилия"))
        item = self.tableDrivers.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.tableDrivers.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Отчество"))
        item = self.tableDrivers.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Стаж"))
        self.btn_addWorkDone.setText(_translate("MainWindow", "Добавить"))
        self.btn_deleteWorkDone.setText(_translate("MainWindow", "Удалить"))
        self.btn_editWorkDone.setText(_translate("MainWindow", "Изменить данные"))
        item = self.tableWorkDone.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWorkDone.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Код маршрута"))
        item = self.tableWorkDone.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Код водителя"))
        item = self.tableWorkDone.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Дата отправки"))
        item = self.tableWorkDone.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Дата возвращения"))
        item = self.tableWorkDone.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Премия"))
        self.btn_page_routs.setText(_translate("MainWindow", "Маршруты"))
        self.btn_page_drivers.setText(_translate("MainWindow", "Водители"))
        self.btn_page_workDone.setText(_translate("MainWindow", "Проделанная работа"))
